# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Mehdi Daanoune | Portfolio"
email: "mehdi.daanoune@gmail.com"
description: >-
  Senior R&D Engineer | Modeling, Simulation & Data Science | 13+ patents | Python, Machine Learning, Innovation.
twitter_username: 
github_username: DmHoly
minimal_mistakes_skin: mint
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
  - assets/css

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

author:
  name   : "Mehdi Daanoune"
  avatar : "/assets/images/avatar.png"
  bio    : "Senior R&D Engineer specializing in physical modeling (optics and semiconductors), automation, advanced analytics, and machine learning."
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/mehdi-daanoune"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/DmHoly"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:mehdi.daanoune@gmail.com"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/mehdi-daanoune"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/DmHoly"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:mehdi.daanoune@gmail.com"

header:
  overlay_image: /assets/images/banner.png 
  overlay_filter: 0.2 # effet foncé
  caption: "Welcome to my Portfolio"
  actions:
    - label: "Découvrir mes projets"
      url: "/projects/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
